To perform Simple Linear Regression and find out the coefficient of it.


In [1]:
#Roll No. 23
#Name - Komal Gulhane
#Date - 15-02-24
#Subject - Big Data Analytics 
#Section - B

In [37]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
import warnings
warnings.filterwarnings('ignore')
from sklearn.linear_model import LinearRegression

In [4]:
import matplotlib.pyplot as plt

In [5]:
import os

In [6]:
os.getcwd()

'C:\\Users\\Komal'

In [7]:
os.chdir('C:\\Users\\Komal\\Desktop')

In [8]:
data=pd.read_csv('IRIS.csv')

In [9]:
data.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [10]:
data.tail()

sepal_length  sepal_width  petal_length  petal_width         species
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [12]:
data.describe

<bound method NDFrame.describe of      sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]>

In [13]:
data.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [14]:
data.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [62]:
# Assiging values in X & Y
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values


In [63]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [64]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [65]:
x_train,x_test,y_train,y_test = train_test_split(x,y)

In [66]:
y_train

array([0, 2, 1, 0, 0, 1, 0, 0, 2, 1, 2, 2, 2, 1, 1, 1, 0, 0, 1, 2, 2, 1,
       1, 0, 1, 0, 0, 0, 2, 2, 2, 2, 1, 0, 2, 0, 0, 2, 2, 1, 0, 1, 0, 2,
       2, 1, 0, 2, 1, 2, 0, 0, 0, 2, 0, 0, 1, 1, 1, 2, 1, 0, 0, 2, 1, 2,
       2, 2, 1, 1, 1, 2, 1, 1, 0, 2, 0, 2, 2, 2, 1, 2, 0, 0, 0, 2, 0, 1,
       0, 2, 1, 2, 1, 1, 2, 1, 0, 2, 2, 2, 0, 0, 2, 1, 1, 1, 1, 2, 1, 0,
       0, 2])

In [67]:
y_test

array([2, 0, 0, 1, 2, 2, 0, 2, 1, 0, 1, 2, 1, 2, 1, 0, 1, 2, 2, 0, 2, 1,
       0, 0, 0, 1, 1, 0, 2, 1, 0, 0, 1, 1, 1, 1, 0, 0])

In [68]:
x_train

array([[4.9, 3.1, 1.5, 0.1],
       [6.7, 3.3, 5.7, 2.5],
       [6.1, 3. , 4.6, 1.4],
       [4.3, 3. , 1.1, 0.1],
       [5.4, 3.4, 1.5, 0.4],
       [5.1, 2.5, 3. , 1.1],
       [4.4, 3.2, 1.3, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [7.2, 3.6, 6.1, 2.5],
       [5.6, 2.7, 4.2, 1.3],
       [6.7, 3.3, 5.7, 2.1],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [5. , 2. , 3.5, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [5.5, 2.3, 4. , 1.3],
       [4.9, 3. , 1.4, 0.2],
       [5.1, 3.8, 1.5, 0.3],
       [5.8, 2.6, 4. , 1.2],
       [6.4, 3.1, 5.5, 1.8],
       [7.3, 2.9, 6.3, 1.8],
       [6. , 2.9, 4.5, 1.5],
       [6.7, 3.1, 4.4, 1.4],
       [4.8, 3.4, 1.6, 0.2],
       [6.6, 3. , 4.4, 1.4],
       [5.5, 3.5, 1.3, 0.2],
       [4.5, 2.3, 1.3, 0.3],
       [4.6, 3.4, 1.4, 0.3],
       [7.1, 3. , 5.9, 2.1],
       [6.9, 3.1, 5.1, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [6.3, 2.9, 5.6, 1.8],
       [6.2, 2.9, 4.3, 1.3],
       [5.5, 4.2, 1.4, 0.2],
       [5.6, 2

In [69]:
x_test

array([[6.1, 3. , 4.9, 1.8],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.4, 1.7, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [7.2, 3.2, 6. , 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [4.8, 3.1, 1.6, 0.2],
       [7.4, 2.8, 6.1, 1.9],
       [6.8, 2.8, 4.8, 1.4],
       [5.7, 4.4, 1.5, 0.4],
       [6.7, 3.1, 4.7, 1.5],
       [7.2, 3. , 5.8, 1.6],
       [6.6, 2.9, 4.6, 1.3],
       [5.9, 3. , 5.1, 1.8],
       [5.6, 2.5, 3.9, 1.1],
       [5.1, 3.7, 1.5, 0.4],
       [5.7, 2.8, 4.1, 1.3],
       [6.2, 2.8, 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [5.8, 4. , 1.2, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [5.5, 2.4, 3.8, 1.1],
       [4.6, 3.1, 1.5, 0.2],
       [5.4, 3.9, 1.3, 0.4],
       [4.4, 2.9, 1.4, 0.2],
       [6. , 3.4, 4.5, 1.6],
       [5.8, 2.7, 4.1, 1. ],
       [5. , 3.3, 1.4, 0.2],
       [4.9, 2.5, 4.5, 1.7],
       [5.7, 3. , 4.2, 1.2],
       [4.6, 3.2, 1.4, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [6.3, 3.3, 4.7, 1.6],
       [5.5, 2.4, 3.7, 1. ],
       [5.2, 2

In [70]:
from sklearn.linear_model import LinearRegression
model = LinearRegression().fit(x_train,y_train)
model.score(x_train,y_train)

0.9319925574313357

In [71]:
#Assigning Coefficient (slope) to m
m = model.coef_

In [72]:
print("Coeficient :", m)

Coeficient : [-0.08988211 -0.04317916  0.21495751  0.60993295]


In [73]:
#Assigning Y-intercept to n
n = model.intercept_

In [74]:
print("Intercept : ", n)

Intercept :  0.10568926599621464


In [75]:
model.score(x_test,y_test) * 100

92.19869786189734

In [76]:
data.isnull().any()

sepal_length    False
sepal_width     False
petal_length    False
petal_width     False
species         False
dtype: bool